Repository alex13lopez/gcloud-backup, pull requests merged in 2020-10, with the labels that each got.

#6 Ver: 9.6b - Fix CygWin - All commands implemented with CygWin
  GcloudBackup.ps1
Labels: bug, enhancement

#8 Ver: 9.7b - enhancement/getdatefromcloud
  GcloudBackup.ps1
Labels: enhancement

#13 Ver: 9.7.1b - Fixed the names with spaces problem
  GcloudBackup.ps1
Labels: bug

#14 Ver: 9.7.2b - Fixes the RemoveOld with Spaces
  .gitignore
  GcloudBackup.ps1
  GcloudConf.ps1
  README.md
Labels: bug
